[package]
org = "wso2"
name = "Company_create_count_delete"
version = "0.1.0"
distribution = "2201.10.3"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "hubspot.crm.obj.companies"
version = "1.0.0"
repository = "local"
